
# constants used in test_flags[]
RETRY_MOTION_EMAIL = 100
JUST_PRINT_MESSAGE = 101
USE_MOCK_MAILMAN = 102
#BUTTON_PRESSED = 103
DISPLAY_ACTIVITY = 104
FAST_RETRY = 105
MOCK_ERROR = 106
FAST_MODE = 107
PRINT_MONITOR = 108
PRINT_WEB_SERVER_ACTIVITY = 109

#constants used in display update
MOTION_REPORT_SENT = 1001
MOTION_SENSOR_TRIPPED = 1002
BUTTON_EMAIL_SENT = 1003
EMAIL_RETRY = 1004
HOUR_TICK = 1005
BUTTON_PRESSED = 1006
RETRY_MOTION_EMAIL = 1007

dadivity_event_name = {
MOTION_REPORT_SENT:"MOTION_REPORT_SENT",
MOTION_SENSOR_TRIPPED:"MOTION_SENSOR_TRIPPED",
BUTTON_EMAIL_SENT:"BUTTON_EMAIL_SENT",
EMAIL_RETRY:"EMAIL_RETRY",
HOUR_TICK:"HOUR_TICK",
BUTTON_PRESSED:"BUTTON_PRESSED",
RETRY_MOTION_EMAIL:"RETRY_MOTION_EMAIL",
}

